# GENERATED BY GEMINI

import re

# The source Dart strings (You can also read this from a file)
dart_content = """
Map<String, Map<String, List<dynamic>>> voices = {
  "Arabic (\\u0627\\u0644\\u0639\\u0631\\u0628\\u064a\\u0629)": {
    "Kareem - Low": [
      "16000",
      "ar_JO",
      "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ar/ar_JO/kareem/low/ar_JO-kareem-low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ar/ar_JO/kareem/low/ar_JO-kareem-low.onnx.json?download=true",
      "ar_JO-kareem-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ar/ar_JO/kareem/low/samples/speaker_:speaker_id:.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/ar/ar_JO/kareem/low/MODEL_CARD?download=true",
      {}
    ]
  }
};
"""


def extract_urls(list_items):
    """Identifies the correct URL by looking at strings inside the list."""
    onnx = ""
    json = ""
    example = ""

    for item in list_items:
        # Strip quotes and whitespace
        val = item.strip().strip('"').strip("'")

        if val.endswith(".onnx?download=true"):
            onnx = val
        elif val.endswith(".json?download=true"):
            json = val
        elif "/samples/" in val:
            example = val

    return onnx, json, example


def convert_dart_to_rust(content):
    # Regex to find the voice name and its associated list
    # Matches: "Voice Name": [ ... ]
    pattern = r'"([^"]+)":\s*\[(.*?)\]'
    matches = re.findall(pattern, content, re.DOTALL)

    rust_output = [
        "static PIPER_VOICES: phf::Map<&'static str, phf::Map<&'static str, PiperVoice<'static>>> = phf::phf_map! {"
    ]

    # In your example, Rust keys are the locale (ar_JO), not the language name
    # We find the locale inside the list to use as the top-level key
    locales_found = {}

    for voice_name, list_content in matches:
        items = list_content.split(",")
        onnx, json, example = extract_urls(items)

        # Identify locale (usually the second item or 5-char string like ar_JO)
        locale = "unknown"
        for item in items:
            val = item.strip().strip('"')
            if len(val) == 5 and "_" in val:
                locale = val
                break

        if locale not in locales_found:
            locales_found[locale] = []

        voice_entry = (
            f'        "{voice_name}" => PiperVoice {{\n'
            f'            example: "{example}",\n'
            f'            onnx: "{onnx}",\n'
            f'            json: "{json}"\n'
            f"        }}"
        )
        locales_found[locale].append(voice_entry)

    # Build the final string
    for locale, voices in locales_found.items():
        rust_output.append(f'    "{locale}" => phf::phf_map! {{')
        rust_output.append(",\n".join(voices))
        rust_output.append("    },")

    rust_output.append("};")
    return "\n".join(rust_output)


print(convert_dart_to_rust(dart_content))
