name: Build
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Just
        uses: extractions/setup-just@v3
      - name: Install NPM
        uses: actions/setup-node@v5
      - name: Install Bun
        run: npm install -g bun
      - name: Install dependencies
        run: bun i --frozen-lockfile
      - name: Build-Linux
        run: just b
      - name: Install cargo-xwin
        run: cargo install --locked cargo-xwin
      - name: Build-Windows
        run: just bw
